apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keycloak-db
  name: keycloak-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: keycloak-db
    spec:
      containers:
        - env:
            - name:  POSTGRES_DB
              value: keycloak
            - name: POSTGRES_USER
              value: keycloak
            - name: POSTGRES_PASSWORD
              value: password
          image: postgres
          name: keycloak-db
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: keycloak-db-claim0
      restartPolicy: Always
      volumes:
        - name: keycloak-db-claim0
          persistentVolumeClaim:
            claimName: keycloak-db-claim0
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: keycloak-db-claim0
  name: keycloak-db-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}